# Generated by Django 2.2.3 on 2019-08-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizzerias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pizzeria', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('categories', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('keys', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('menuPageURL', models.CharField(max_length=200)),
                ('menusamountMax', models.CharField(max_length=200)),
                ('menusamountMin', models.CharField(max_length=200)),
                ('menuscurrency', models.CharField(max_length=200)),
                ('menusdateSeen', models.CharField(max_length=200)),
                ('menusdescription', models.CharField(max_length=200)),
                ('menusname', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('postalCode', models.CharField(max_length=200)),
                ('priceRangeCurrency', models.CharField(max_length=200)),
                ('priceRangeMin', models.CharField(max_length=200)),
                ('priceRangeMax', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='toolinput',
            name='tool',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
        migrations.DeleteModel(
            name='ToolInput',
        ),
    ]
