# Generated by Django 2.2.3 on 2019-08-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_auto_20190808_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzerias',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
